---
all:
  hosts:
    node0:
      ansible_host: "10.10.100.25"
      env_node_prefix: "ANSIBLE_NODE0_"
    node1:
      ansible_host: "10.10.100.26"
      env_node_prefix: "ANSIBLE_NODE1_"

  vars:
    vault_secret: "{{ vault_secret_path }}/{{ env }}/{{ inventory_hostname }}"
    ansible_port: "{{ lookup(vault_module, vault_secret, **vault_data).secret.ansible_port }}"
    ansible_user: "{{ lookup(vault_module, vault_secret, **vault_data).secret.ansible_user }}"
    ansible_password: "{{ lookup(vault_module, vault_secret, **vault_data).secret.ansible_password }}"
    root_password: "{{ lookup(vault_module, vault_secret, **vault_data).secret.root_password }}"
    init_root_password: "{{ lookup(vault_module, vault_secret, **vault_data).secret.init_root_password }}"
    init_ansible_port: "{{ lookup(vault_module, vault_secret, **vault_data).secret.init_ansible_port }}"
    init_ansible_user: "{{ lookup(vault_module, vault_secret, **vault_data).secret.init_ansible_user }}"
    init_ansible_password: "{{ lookup(vault_module, vault_secret, **vault_data).secret.init_ansible_password }}"

nodes:
  hosts:
    node0:
    node1:
